apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  AWS_BUCKET: udagram-shenry-13277
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  JWT_SECRET: hello
  POSTGRES_DB: postgres
  POSTGRES_HOST: udagram-db.cqsztjfp6yxe.us-east-1.rds.amazonaws.com
  URL: http://localhost:8100
